services:
    command_bus_console.command_collector:
        class: Clearcode\CommandBusConsole\CommandCollector

    command_bus_console.value_conveters.uuid:
        class: Clearcode\CommandBusConsole\ValueConverter\UuidConverter

    command_bus_console.value_conveters.int:
        class: Clearcode\CommandBusConsole\ValueConverter\IntConverter

    command_bus_console.arguments_processor:
        class: Clearcode\CommandBusConsole\ArgumentsProcessor
        arguments:
            - [@command_bus_console.value_conveters.uuid, @command_bus_console.value_conveters.int]

    command_bus_console.command_launcher:
        class: Clearcode\CommandBusConsole\CommandLauncher
        arguments:
            - @command_bus_console.command_collector
            - @command_bus_console.arguments_processor