services:
    command_bus_launcher.command_collector:
        class: ClearcodeHQ\CommandBusLauncherBundle\Launcher\CommandCollector

    command_bus_launcher.value_conveters.uuid:
        class: ClearcodeHQ\CommandBusLauncherBundle\Launcher\ValueConverter\UuidConverter

    command_bus_launcher.value_conveters.int:
        class: ClearcodeHQ\CommandBusLauncherBundle\Launcher\ValueConverter\IntConverter

    command_bus_launcher.arguments_processor:
        class: ClearcodeHQ\CommandBusLauncherBundle\Launcher\ArgumentsProcessor
        arguments:
            - [@command_bus_launcher.value_conveters.uuid, @command_bus_launcher.value_conveters.int]

    command_bus_launcher.command_launcher:
        class: ClearcodeHQ\CommandBusLauncherBundle\Launcher\CommandLauncher
        arguments:
            - @command_bus_launcher.command_collector
            - @command_bus_launcher.arguments_processor