services:
    command_bus_console.command_form_type_map:
        class: Clearcode\CommandBusConsole\CommandFormTypeMap

    command_bus_console.console.event_listener.set_form_type_of_form_based_command:
        class: Clearcode\CommandBusConsole\Console\EventListener\SetFormTypeOfFormBasedCommandEventListener
        arguments:
            - "@command_bus_console.command_form_type_map"
        tags:
            - { name: kernel.event_listener, event: console.command, method: onConsoleCommand, priority: 2048 }
